[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py migrate --noinput",
    "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "gunicorn thehybridprotocol.wsgi:application --bind 0.0.0.0:$PORT" 