[phases.setup]
nixPkgs = ["python313", "postgresql"]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python3 manage.py migrate --noinput",
    "python3 manage.py collectstatic --noinput --clear"
]

[start]
cmd = "gunicorn thehybridprotocol.wsgi:application --bind 0.0.0.0:$PORT" 