[build]
builder = "NIXPACKS"

[deploy]
startCommand = """
python manage.py migrate --noinput &&
python manage.py collectstatic --noinput &&
gunicorn thehybridprotocol.wsgi:application --bind 0.0.0.0:$PORT
"""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10