[build]
builder = "NIXPACKS"

[deploy]
startCommand = "mkdir -p staticfiles media && python manage.py test_db_connection && python manage.py migrate --noinput && python manage.py create_admin && python manage.py collectstatic --noinput --clear && gunicorn thehybridprotocol.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10