[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python scripts/deploy_railway.py && gunicorn thehybridprotocol.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10