[build]
builder = "NIXPACKS"
providers = ["python"]
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "bash -lc 'cd backend && celery -A thehybridprotocol worker -l info'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10