[build]
builder = "NIXPACKS"
providers = ["python"]             # force Python so pip exists

[deploy]
startCommand = "bash -lc 'pip install -r backend/requirements.txt && cd backend && celery -A thehybridprotocol worker -l info'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10