[build]
builder = "NIXPACKS"
providers = ["python"]
buildCommand = "/opt/venv/bin/pip install -r backend/requirements.txt"

[deploy]
startCommand = "bash -lc 'cd backend && /opt/venv/bin/celery -A thehybridprotocol worker -l info'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10