[build]
builder = "NIXPACKS"
providers = ["python"]

[deploy]
startCommand = "bash -lc '/opt/venv/bin/pip install -r backend/requirements.txt && cd backend && /opt/venv/bin/celery -A thehybridprotocol worker -l info'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10