# Generated by Django 4.2.23 on 2025-07-30 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastepisode',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='apple_url',
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Episode cover image', null=True, upload_to='podcast_covers/'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='script',
            field=models.TextField(blank=True, help_text='Full episode script or transcript'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration in format: HH:MM:SS', max_length=20),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, help_text='Episode number (optional)', null=True, unique=True),
        ),
    ]
