# Generated by Django 4.2.23 on 2025-07-30 06:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_podcastepisode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='publish_date',
            field=models.DateField(default=core.models.get_current_date),
        ),
    ]
