# Generated by Django 4.2.23 on 2025-07-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_podcastepisode_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for newsletter', null=True, upload_to='newsletter_images/'),
        ),
    ]
