# Generated by Django 4.2.23 on 2025-08-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newsletter_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizedElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(help_text='English text', max_length=500)),
                ('spanish', models.CharField(help_text='Spanish text', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Localized Element',
                'verbose_name_plural': 'Localized Elements',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TextWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Widget image', null=True, upload_to='widget_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(help_text='Localized widget content', on_delete=django.db.models.deletion.CASCADE, related_name='widget_contents', to='core.localizedelement')),
                ('title', models.ForeignKey(help_text='Localized widget title', on_delete=django.db.models.deletion.CASCADE, related_name='widget_titles', to='core.localizedelement')),
            ],
            options={
                'verbose_name': 'Text Widget',
                'verbose_name_plural': 'Text Widgets',
                'ordering': ['order', 'title__english'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(help_text='Localized tag name', on_delete=django.db.models.deletion.CASCADE, related_name='tag_names', to='core.localizedelement')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name__english'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of items in this category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(help_text='Localized category name', on_delete=django.db.models.deletion.CASCADE, related_name='category_names', to='core.localizedelement')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name__english'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Year')),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of items in this archive')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
