# Generated by Django 4.2.23 on 2025-08-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_localizedelement_textwidget_tag_category_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category for this newsletter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='core.category'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for this newsletter', related_name='newsletters', to='core.tag'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category for this episode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_episodes', to='core.category'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for this episode', related_name='podcast_episodes', to='core.tag'),
        ),
    ]
