# Generated by Django 4.2.23 on 2025-08-03 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsletter_category_newsletter_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content (max 2000 characters)', max_length=2000)),
                ('author_name', models.CharField(help_text="Author's display name", max_length=100)),
                ('author_email', models.EmailField(help_text="Author's email address", max_length=254)),
                ('author_website', models.URLField(blank=True, help_text="Author's website (optional)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this comment has been approved for display')),
                ('newsletter', models.ForeignKey(blank=True, help_text='Related newsletter (if this is a newsletter comment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.newsletter')),
                ('podcast_episode', models.ForeignKey(blank=True, help_text='Related podcast episode (if this is a podcast comment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.podcastepisode')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('newsletter__isnull', True), ('podcast_episode__isnull', False)), models.Q(('newsletter__isnull', False), ('podcast_episode__isnull', True)), _connector='OR'), name='comment_must_belong_to_one_content_type'),
        ),
    ]
