# Generated by Django 4.2.23 on 2025-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='available_in_english',
            field=models.BooleanField(default=True, help_text='Content is available in English'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='available_in_spanish',
            field=models.BooleanField(default=False, help_text='Content is available in Spanish'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='available_in_english',
            field=models.BooleanField(default=True, help_text='Content is available in English'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='available_in_spanish',
            field=models.BooleanField(default=False, help_text='Content is available in Spanish'),
        ),
    ]
