# Generated by Django 4.2.23 on 2025-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newsletter_available_in_english_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook URL', null=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='spotify_url',
            field=models.URLField(default='https://open.spotify.com/', help_text='Spotify episode URL'),
        ),
    ]
