# Generated by Django 4.2.23 on 2025-08-10 00:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_podcastepisode_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Full newsletter content with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='excerpt',
            field=ckeditor.fields.RichTextField(help_text='Brief description for previews with basic formatting', max_length=500),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Episode description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='script',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full episode script or transcript with rich text formatting'),
        ),
    ]
