# Generated by Django 4.2.23 on 2025-08-10 01:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_newsletter_content_alter_newsletter_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=ckeditor.fields.RichTextField(help_text='Newsletter title with basic formatting', max_length=200),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='title',
            field=ckeditor.fields.RichTextField(help_text='Episode title with basic formatting', max_length=200),
        ),
    ]
