# Generated by Django 4.2.23 on 2025-08-10 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_newsletter_title_alter_podcastepisode_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignup',
            name='bounce',
            field=models.BooleanField(default=False, help_text='Whether email has bounced'),
        ),
        migrations.AddField(
            model_name='emailsignup',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Whether user is subscribed to newsletters'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='preheader',
            field=models.CharField(blank=True, help_text='Preview text shown in email clients', max_length=200),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='send_key',
            field=models.CharField(default='', help_text='Unique key for sending operations', max_length=50),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When newsletter was sent to subscribers', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Newsletter status', max_length=20),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='', help_text='Email subject line', max_length=200),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, help_text="Provider's message ID", max_length=255, null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(help_text='Newsletter that was sent', on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.newsletter')),
                ('recipient', models.ForeignKey(help_text='Recipient of the email', on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.emailsignup')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('newsletter', 'recipient')},
            },
        ),
    ]
