# Generated by Django 4.2.23 on 2025-01-15 00:00

from django.db import migrations
import uuid


def generate_send_keys(apps, schema_editor):
    """Generate unique send_key values for existing newsletters"""
    Newsletter = apps.get_model('core', 'Newsletter')
    
    for newsletter in Newsletter.objects.all():
        if not newsletter.send_key or newsletter.send_key == "":
            newsletter.send_key = str(uuid.uuid4())
            newsletter.save()


def reverse_generate_send_keys(apps, schema_editor):
    """Reverse operation - clear send_key values"""
    Newsletter = apps.get_model('core', 'Newsletter')
    
    for newsletter in Newsletter.objects.all():
        newsletter.send_key = ""
        newsletter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emailsignup_bounce_emailsignup_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_send_keys, reverse_generate_send_keys),
    ]
