# Generated by Django 4.2.23 on 2025-08-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_newsletter_send_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='send_key',
            field=models.CharField(default='', help_text='Unique key for sending operations', max_length=50, unique=True),
        ),
    ]
